[package]
name = "open_art_market"
version = "0.0.1"

[dependencies]
# Keep the version in sync with bootstrap.sh and Dockerfile
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.5.0" }

[addresses]
open_art_market = "0x0"
