#!/usr/bin/env bash
# This script fails if the git working copy is dirty, and prints the diff
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=${SCRIPT_DIR}/..

# Some files are allowed to be dirty. We'll restore these before checking.
git checkout ${ROOT_DIR}/.envrc

diff=$(git diff)
if [[ ! -z "${diff}" ]]; then
  >&2 echo "The working copy is dirty:"
  >&2 echo "${diff}"
  exit 1
fi
