[package]
name = "coownable"
version = "1.0.0"

[dependencies]
# Keep the version in sync with scripts/install-sui.sh
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.71.1" }

[addresses]
coownable = "0x0"
