name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: oam-runners
    steps:
    - uses: actions/checkout@v3
    - run: ./scripts/asdf-install.sh
    - uses: HatsuneMiku3939/direnv-action@v1
    - run: ./scripts/sui-install.sh
    - run: rm -rf ~/.sui
    - run: sui start > sui.log 2>&1 &
    - run: sleep 5
    - run: ./scripts/sui-new-addresses.sh
    - run: npm ci
    - run: direnv exec . ./scripts/publish-contracts.sh
    - run: direnv exec . npm test
    - run: npm run compile
    - run: ./scripts/fail-if-dirty
    - name: Print environment variables
      run: |
        cat .sui.env
      if: ${{ always() }}
    - name: Print sui log
      run: |
        cat sui.log
      if: ${{ always() }}
    - name: Kill sui
      run: |
        sudo kill -9 $(ps aux | grep sui | grep -v grep | awk '{print $2}')
      if: ${{ always() }}
    

    