name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker compose up -d
    - run: ./scripts/wait-for-file ../output/contracts.json 120
    - run: npm ci && cd setup && npm ci
    - run: ./scripts/json-to-env.sh && npm run create:artwork-display
    - run: ./scripts/json-to-env.sh && npm run create:artwork-shard-display
    - run: ./scripts/json-to-env.sh && npm test
    