name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: oam-runners
    steps:
    - uses: actions/checkout@v3
    - uses: HatsuneMiku3939/direnv-action@v1
    - run: cat ./.tool-versions | cut -d' ' -f1 | xargs -n 1 asdf plugin add || echo "asdf plugins installed"
    - run: asdf install
    - run: cargo install --locked --git https://github.com/MystenLabs/sui.git --tag testnet-v1.5.0 sui
    - run: cargo install --git https://github.com/move-language/move move-analyzer --branch sui-move --features "address32"
    - run: asdf reshim
    - run: docker compose up -d
    - run: ./scripts/wait-for-file ./output/contract.json 300
    - run: npm ci && cd setup && npm ci
    - run: ./scripts/json-to-env.sh
    - run: direnv allow
    - run: cd setup && direnv exec . npm run create:artwork-display
    - run: cd setup && direnv exec . npm run create:artwork-shard-display
    - run: direnv exec . npm test
    - run: npm run format
    - run: npm run lint
    - run: npm run compile
    - run: ./scripts/fail-if-dirty
    - name: Print docker logs
      run: |
        docker compose logs > docker.log
        cat docker.log
      if: ${{ always() }}

    