name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js with asdf
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1
        echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc
        echo '. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
        export PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"
        source ~/.bashrc
    - run: cat ./.tool-versions | cut -d' ' -f1 | xargs -n 1 asdf plugin add || echo "asdf plugins installed"

    - name: Install sui dependencies
      run: ./scripts/bootstrap.sh

    - name: Start Sui
      run: sui start

    - name: Install npm dependencies
      run: npm ci && cd setup && npm ci

    - name: Deploy contracts
      run: ./scripts/setup-oam-on-local-node.sh

    - name: Run tests
      run: direnv exec . npm test
    