name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: oam-runners
    steps:
    - uses: actions/checkout@v3
    - uses: HatsuneMiku3939/direnv-action@v1
    - run: cat ./.tool-versions | cut -d' ' -f1 | xargs -n 1 asdf plugin add || echo "asdf plugins installed"
    - run: asdf install
    # - run: cargo install --locked --git https://github.com/MystenLabs/sui.git --tag testnet-v1.5.0 sui
    # - run: cargo install --git https://github.com/move-language/move move-analyzer --branch sui-move --features "address32"
    # - run: asdf reshim
    - run: rm -rf ~/.sui
    - run: sui start > sui.log 2>&1 &
    - run: sleep 5
    - run: npm ci
    - run: ./scripts/setup-local-node.sh
    - run: direnv exec . npm test
    - run: npm run format
    - run: npm run lint
    - run: npm run build
    - run: ./scripts/fail-if-dirty
    - name: Print sui log
      run: |
        cat sui.log
      if: ${{ always() }}
    - name: Kill sui
      run: |
        sudo kill -9 $(ps aux | grep sui | grep -v grep | awk '{print $2}')
      if: ${{ always() }}
    

    