name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-sui-localnet:
    runs-on: oam-runners
    steps:
    - uses: actions/checkout@v3
    - run: ./scripts/asdf-install.sh
    - uses: HatsuneMiku3939/direnv-action@v1
    - run: ./scripts/sui-install.sh
    - run: rm -rf ~/.sui
    - run: sui start > sui.log 2>&1 &
    - run: sleep 5
    - run: ./scripts/sui-new-addresses.sh
    - run: npm ci
    - run: direnv exec . ./scripts/publish-contracts.sh
    - run: direnv exec . npm test
    - run: direnv exec . npm test
      env:
        SHINAMI_ENABLED: "1"
        ADMIN_CAP_ID: ${{secrets.ADMIN_CAP_ID}}
        PACKAGE_ID: ${{secrets.PACKAGE_ID}}
        ADMIN_ADDRESS: ${{secrets.ADMIN_ADDRESS}}
        ADMIN_PHRASE: ${{secrets.ADMIN_PHRASE}}
        SHINAMI_ACCESS_KEY: ${{secrets.SHINAMI_ACCESS_KEY}}
        SUI_NETWORK: 'testnet'
    - run: npm run compile
    - run: ./scripts/fail-if-dirty
    - name: Print environment variables
      run: |
        cat .sui.env
      if: ${{ always() }}
    - name: Print sui log
      run: |
        cat sui.log
      if: ${{ always() }}
    - name: Kill sui
      run: |
        sudo kill -9 $(ps aux | grep sui | grep -v grep | awk '{print $2}')
      if: ${{ always() }}
  test-shinami-testnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
    - run: npm ci
    - run: direnv exec . npm test
      env:
        SHINAMI_ENABLED: "1"
        ADMIN_CAP_ID: ${{secrets.ADMIN_CAP_ID}}
        PACKAGE_ID: ${{secrets.PACKAGE_ID}}
        ADMIN_ADDRESS: ${{secrets.ADMIN_ADDRESS}}
        ADMIN_PHRASE: ${{secrets.ADMIN_PHRASE}}
        SHINAMI_ACCESS_KEY: ${{secrets.SHINAMI_ACCESS_KEY}}
        SUI_NETWORK: 'testnet'
