name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker compose up -d
    - run: ./scripts/wait-for-file ./output/contract.json 300
    - run: npm ci && cd setup && npm ci
    - run: ./scripts/json-to-env.sh && cd setup && npm run create:artwork-display
    - run: ./scripts/json-to-env.sh && cd setup && npm run create:artwork-shard-display
    - run: ./scripts/json-to-env.sh && npm test
    - name: Print docker logs
      run: |
        docker compose logs > docker.log
        cat docker.log
      if: ${{ always() }}

    