# https://www.oddbird.net/2022/06/01/dependabot-single-pull-request/
name: Upgrade dependencies

env:
  PATH: /home/gha/.asdf/shims:/home/gha/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

on:
  workflow_dispatch: # Allow running on-demand
  schedule:
    # Runs every night at 04:10 UTC
    - cron: '10 4 * * *'

jobs:
  upgrade:
    name: Create Upgrade PR
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/asdf-install.sh
      - run: npm ci
      - run: npm run upgrade
      - name: Open pull request if needed
        run: ./scripts/gha-open-pr.sh auto-dependency-upgrades "Automated dependency upgrades" "package.json"
        env:
          # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          GITHUB_TOKEN: ${{ secrets.GHA_PR_GITHUB_TOKEN }}
